### ISSUE TITLE
Please add semantic version tags

### ISSUE THREAD

**Issue by horatio-sans-serif** [mapedd/TKDragView#1]
I’ve recently added [`<TKDragView>`](https://github.com/fictorial/Specs/blob/master/TKDragView/1.0.0/TKDragView.podspec) to the [CocoaPods](https://github.com/CocoaPods/CocoaPods) package manager repo -- in my fork thereof actually.

CocoaPods is a tool for managing dependencies for OSX and iOS Xcode projects and provides a central repository for iOS/OSX libraries. This makes adding libraries to a project and updating them extremely easy and it will help users to resolve dependencies of the libraries they use.

However, `<TKDragView>` doesn't have any version tags. I’ve added the current HEAD as version 1.0.0, but a version tag will make dependency resolution much easier.

[Semantic version](http://semver.org) tags (instead of plain commit hashes/revisions) allow for [resolution of cross-dependencies](https://github.com/CocoaPods/Specs/wiki/Cross-dependencies-resolution-example).

In case you didn’t know this yet; you can tag the current HEAD as, for instance, version 1.0.0, like so:

```
$ git tag -a 1.0.0 -m "Tag release 1.0.0"
$ git push --tags
```

**Comment by mapedd** [comment]
Great!
Thanks for adding `<TKDragView>` to CocoaPods, i was planning to do that in the near future.

I made this :

```
$ git tag -a 1.0.0 -m "Tag release 1.0.0"
$ git push --tags
```

to create a tag, tell me if it works, cause i'm not tags atm.

**Comment by mapedd** [comment]
If everything is fine with tags, please feel free to make a Pull Request so that i can add podspec file to the main repository :D
