### ISSUE TITLE
It allows overlaying on same frames.

### ISSUE THREAD

**Issue by cloudjanak** [mapedd/TKDragView#12]
https://www.dropbox.com/s/2kb95e073kvn7x6/TKDragView.mov?dl=0

you can see video from above link.
Thank you.

**Comment by mapedd** [comment]
Do you have a bit of time to take a look of the reason?

**Comment by cloudjanak** [comment]
i had tried my best can you please help me ??i am new to iPhone.

**Comment by cloudjanak** [comment]
i need last help don't allow overlaying.

**Comment by cloudjanak** [comment]
For this only my game is not moving ahead.

**Comment by iossolution** [comment]
i am facing same issue @mapedd

**Comment by cloudjanak** [comment]
can you please help me sir ?

**Comment by cloudjanak** [comment]
This small help will solve my big problem
i need this help for below project.
![ios simulator screen shot 07-jul-2015 10 27 47 am](https://cloud.githubusercontent.com/assets/7457258/8539031/bcc8f6e4-2493-11e5-9917-8fec3a83bb5f.png)

**Comment by cloudjanak** [comment]
Hi iossolution you have any idea to resolve this ??
