### ISSUE TITLE
Use UIViews instead of CGRects as a targets - will be easier to perform rotations, animations…  

### ISSUE THREAD

**Issue by horatio-sans-serif** [mapedd/TKDragView#2]
From your TODO list: "Use UIViews instead of CGRects as a targets - will be easier to perform rotations, animations…"

If you do this, please make it in addition to CGRect!  CGRect targets are very useful in their own right.

**Comment by mapedd** [comment]
I've started using TKDragView again in my client project so probably there will be some action in this repository soon :D

I will not remove CGRects as a targets for sure, they are great way to point to some area on view the without wasting too much memory, plus they are fast to enumarate, so don't worry and thanks for contacting!

**Comment by horatio-sans-serif** [comment]
Great, thanks!
