### ISSUE TITLE
Make the view larger when dragging started

### ISSUE THREAD

**Issue by Ricardo1980** [mapedd/TKDragView#5]
Hello!
In your sample code I see you make the views larger in dragViewDidStartDragging delegate method, but that method is called not when the view is tapped, but when movement is started. I'd like to make it larger when is tapped. What do you recommend me? Perhaps using the tapped: method that in your sample code is empty? But maybe that's a problem when dragging is finished or even not started and dragViewDidEndDragging not called. What do you think? Thanks.

**Comment by mapedd** [comment]
i wlil try to look into that today

**Comment by Ricardo1980** [comment]
Any news about this? or any clue so I could do it for you. Thanks a lot.

**Comment by mapedd** [comment]
I would say you should add new UITapGestureRecognizer if i you want the view to react to user's taps. 
You can subclass or just edit the code after cloning :P
As the name says, this is a TK **Drag** View, it have it's own UIPanGestureRecognizer, which fires only when it recognizes finger movement :D
Sorry for so long delay, cheers!
